services:
  - type: web
    name: flask-backend
    env: docker
    plan: free
    region: frankfurt
    rootDir: backend

  - type: web
    name: react-frontend
    env: docker
    plan: free
    rootDir: frontend
    envVars:
      - key: VITE_BACKEND_URL
        fromService:
          name: flask-backend
          type: web
          envVarKey: RENDER_EXTERNAL_URL