services:
  - type: web
    name: flask-backend
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 2 -k gthread -b 0.0.0.0:$PORT src.app:app
    envVars:
      - key: CORS_ORIGIN
        value: "*"
    healthCheckPath: /api/hello

  - type: web
    name: react-frontend
    runtime: static
    rootDir: frontend
    buildCommand: npm ci && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        value: ""
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"
