version: '3.8'
services:
  backend:
    build:
      context: ../backend
    volumes:
      - ../backend:/app
    ports:
      - "5000:5000"
  frontend:
    build:
      context: ../frontend
    volumes:
      - ../frontend:/app
    ports:
      - "5173:5173"